name: OrangeFox Recovery

on:
  workflow_dispatch:

jobs:
  build:
    name: OFRP Build CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v3
    - name: Installing JDK 7 + Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses5 axel python
    - name: Install OpenJDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'
    - name: Syncing OFRP sources
      run: |
        mkdir ~/OFRP
        cd ~/OFRP
        mkdir ~/.bin
        curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        python3 ~/.bin/repo init --depth=1 -u https://github.com/unlegacy-devices/fox-6.0_manifest -b fox_6.0
        git clone --branch twrp-6.0 --single-branch https://github.com/unlegacy-devices/twrp_device_huawei_y560.git ~/OFRP/device/huawei/y560
        python3 ~/.bin/repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
    - name: Building OFRP
      run: |
        OLDPATH=$PATH
        OLDJAVAHOME=$JAVA_HOME
        export PATH="$HOME/.jdk_7/java-se-7u75-ri/bin:$PATH"
        export JAVA_HOME="$HOME/.jdk_7/java-se-7u75-ri"
        cd ~/OFRP
        git clone https://github.com/NotNoelChannel/android_kernel_huawei_msm8909 -b cm-14.1 ~/OFRP/kernel/huawei/msm8909
        sudo git clone --depth=1 --branch android-7.1.2_r38 --single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8 /opt/toolchains/arm-eabi-4.8
        source build/envsetup.sh
        export OF_MAINTAINER="NotNoelChannel"
        export OF_DISABLE_MIUI_SPECIFIC_FEATURES=1
        export ALLOW_MISSING_DEPENDENCIES=true
        export LC_ALL=C
        export OF_FL_PATH1="/flashlight"
        export OF_LEGACY_SHAR512=1
        export OF_DISABLE_KEYMASTER2=1
        lunch omni_y560-eng
        make -j$(nproc --all) recoveryimage
        export PATH=$OLDPATH
        export JAVA_HOME=$OLDJAVAHOME
    - name: Uploading OFRP builds
      uses: actions/upload-artifact@v3
      with:
        name: ofrp
        path: | 
          /home/runner/OFRP/out/target/product/y560/recovery.*
          /home/runner/OFRP/out/target/product/y560/OrangeFox-*.zip
